export const GET_PROFILE = 'GET_PROFILE';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CREATE_TIMELINE = 'CREATE_TIMELINE';
export const GET_ERRORS = 'GET_ERRORS';
